### Base Spring Config
# Spring Config
spring:
  config:
    import: file:.env[.properties]
  profiles:
    active: default
  application:
    name: catch-mind
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 100
    open-in-view: false
  sql:
    init:
      platform: mysql
      mode: always

#Debug Config
debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Log Config
logging:
  level:
    com.example.Practice: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql: trace

# Exception Handle
server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 8080

# JWT Config
jwt:
  secret-key: ${TOKEN_SECRET}
  access:
    expiration: ${ACCESS_TOKEN_EXPIRATION}
    header: ${ACCESS_TOKEN_HEADER}
  refresh:
    expiration: ${REFRESH_TOKEN_EXPIRATION}
    header: ${REFRESH_TOKEN_HEADER}

# AWS Setting
cloud:
  aws:
    s3:
      bucket: ${BUCKET} # 버킷 환경 변수
      path:
        file: ${BUCKET_FOLDER} # 파일 경로
    region:
      static: ap-northeast-2 # Region (이 경우는 서울)
    stack:
      auto: false
    credentials:
      accessKey: ${S3_ACCESS} # Access Key 환경 변수
      secretKey: ${S3_SECRET} # Secret Access Key 환경 변수

# Swagger Setting
springdoc:
  swagger-ui:
    path: swagger
    # "사용해 보기" 섹션이 기본적으로 활성화 되어야 하는지 여부를 제어
    try-it-out-enabled: true
    # filter 검색
    filter: true
    operations-sorter: method
    # ms 단위 표시
    display-request-duration: true

# Url Setting
url:
  be: ${BE_URL}
  fe: ${FE_URL}
  ai: ${AI_URL}

---
### Local Config
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate

---
### Develop Config
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: validate
